// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9fj4tjNDTP3lgxLTSbwcovESsz0mdwVc',
    appId: '1:113700975452:web:7ac46a959f50f85412c799',
    messagingSenderId: '113700975452',
    projectId: 'campus-connect-360',
    authDomain: 'campus-connect-360.firebaseapp.com',
    storageBucket: 'campus-connect-360.firebasestorage.app',
    measurementId: 'G-2CBG8R221B',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXiMxaYdAz4gGtveY_sIT0Ub9LExxzARw',
    appId: '1:113700975452:ios:7bbf2eacee5a871512c799',
    messagingSenderId: '113700975452',
    projectId: 'campus-connect-360',
    storageBucket: 'campus-connect-360.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXiMxaYdAz4gGtveY_sIT0Ub9LExxzARw',
    appId: '1:113700975452:ios:7bbf2eacee5a871512c799',
    messagingSenderId: '113700975452',
    projectId: 'campus-connect-360',
    storageBucket: 'campus-connect-360.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect360',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9fj4tjNDTP3lgxLTSbwcovESsz0mdwVc',
    appId: '1:113700975452:web:ec4fd0db4089e92312c799',
    messagingSenderId: '113700975452',
    projectId: 'campus-connect-360',
    authDomain: 'campus-connect-360.firebaseapp.com',
    storageBucket: 'campus-connect-360.firebasestorage.app',
    measurementId: 'G-08597VDLGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApHM3wu0WEf2Ui5L4WuZMOfVEzgPcyKQg',
    appId: '1:113700975452:android:85579f22315d35d612c799',
    messagingSenderId: '113700975452',
    projectId: 'campus-connect-360',
    storageBucket: 'campus-connect-360.firebasestorage.app',
  );
}
